apiVersion: v1
kind: Namespace
metadata:
  name: development

---

apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: development
  labels:
    app: nginx-curl
    env: development
spec:
  containers:
    - name: nginx-curl-container
      image: ewoutp/docker-nginx-curl
      ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-hello-rs
  namespace: development
  annotations:
    description: Membuat pod dengan replication ReplicationSet
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx-pod
      - key: env
        operator: In
        values:
          - development
          - production
  template:
    metadata: 
      name: nginx-pod
      labels:
        app: nginx-pod
        env: development
    spec:
      containers:
        - name: nginx-hello-container
          image: nginxdemos/hello
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: development
spec:
  type: NodePort
  selector:
    app: nginx-pod
  ports:
  - port: 80
    targetPort: 80

--- 
#For testing purposes

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: deployment-php
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: php-pod
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-pod
    spec:
      containers:
      - image: bbenns/php-hello-world
        imagePullPolicy: Always
        name: php-pod
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: service-php
spec:
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
  selector:
    app.kubernetes.io/name: php-pod