---

apiVersion: v1
kind: Namespace
metadata:
  name: ns-nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-nginx
  name: deployment-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-pod
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-pod
    spec:
      containers:
      - image: nginxdemos/hello
        imagePullPolicy: Always
        name: nginx-pod
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  namespace: ns-nginx
  name: service-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-pod

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ns-nginx
  name: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: service-nginx
            port:
              number: 80