apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  labels:
    app: nginx-curl
    env: development
spec:
  containers:
    - name: nginx-curl-container
      image: ewoutp/docker-nginx-curl
      ports:
        - containerPort: 80